baseURL = "https://psoh.io/"
defaultContentLanguage = "en"
title = "PowerShell Ohio"
enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
