[[main]]
  name = "Events"
  pageRef = "/events"
  weight = 10

[[main]]
  name = "Speakers"
  pageRef = "/speakers"
  weight = 20

[[main]]
  name = "Resources"
  pageRef = "/resources"
  weight = 30

[[main]]
  name = "About"
  pageRef = "/about"
  weight = 40

[[main]]
  name = "Organizers"
  pageRef = "/organizers"
  weight = 45

[[main]]
  name = "Code of Conduct"
  pageRef = "/code-of-conduct"
  weight = 50

[[main]]
  name = "Meetup"
  url = "https://www.meetup.com/powershellohio/"
  weight = 60

[[footer]]
  name = "Events"
  pageRef = "/events"
  weight = 10

[[footer]]
  name = "Speakers"
  pageRef = "/speakers"
  weight = 20

[[footer]]
  name = "Resources"
  pageRef = "/resources"
  weight = 30

[[footer]]
  name = "About"
  pageRef = "/about"
  weight = 40

[[footer]]
  pre = "github"
  url = "https://github.com/PSOhio"
  weight = 50
